export enum tagTypes {
  user = "user",
  buyer = "buyer",
  seller = "seller",
  moderator = "moderator",
  admin = "admin",
  category = "category",
  subcategory = "subcategory",
  color = "color",
  sizes = "sizes",
  weights = "weights",
  tags = "tags",
  products = "products",
  addToCart = "addToCart",
  booking = "booking",
  review = "review",
  globalDiscount = "globalDiscount",
  localDiscount = "localDiscount",
  promotion = "promotion",
  blogs = "blogs",
  feedback = "feedback",
}

export const tagTypesList = [
  tagTypes.user,
  tagTypes.buyer,
  tagTypes.seller,
  tagTypes.moderator,
  tagTypes.admin,
  tagTypes.category,
  tagTypes.subcategory,
  tagTypes.color,
  tagTypes.weights,
  tagTypes.tags,
  tagTypes.products,
  tagTypes.addToCart,
  tagTypes.booking,
  tagTypes.review,
  tagTypes.globalDiscount,
  tagTypes.localDiscount,
  tagTypes.promotion,
  tagTypes.blogs,
  tagTypes.feedback,
];
